#!/usr/bin/env python

# Built-in modules #
import sys, argparse
from argparse import RawTextHelpFormatter

# Maybe we don't have the pydirdiff library in our sys.path #
try: import pydirdiff
except ImportError: sys.path.insert(0, '/repos/pydirdiff/')
import pydirdiff

# Make a shell arguments parser #
desc = pydirdiff.version_string
parser = argparse.ArgumentParser(description=desc, formatter_class=RawTextHelpFormatter)

# All the required arguments #
parser.add_argument("first_dir", help="The first directory to process", type=str)
parser.add_argument("secnd_dir", help="The second directory to process", type=str)

# All the optional arguments #
parameters = {
    "cmp_fn"        : "Either `md5` or `sizes_only`. Defaults to `md5`.",
    "skip_dsstore"  : "Ignore all '.DS_Store' files. Either `True` or `False`. Defaults to `True`.",
    "skip_dates"    : "Don't print files that just differ in dates. Either `True` or `False`. Defaults to `True`.",
    "verbose"       : "Display current directory as search progresses. Either `True` or `False`. Defaults to `True`.",
    "ignore"        : "Ignore any directories with this name. Defaults to `None`.",
}

# Parse it #
for param, hlp in parameters.items(): parser.add_argument("--" + param, help=hlp)
args      = parser.parse_args()

# Get arguments #
first_dir = args.first_dir
secnd_dir = args.secnd_dir
kwargs    = {k:getattr(args, k) for k in parameters if getattr(args, k) is not None}

# Run the pipeline #
pydirdiff.Analysis(first_dir, secnd_dir, **kwargs).run()
